/**
 * Stillpoint .sketch.md content.
 *
 * This is the visual direction file Spruce's /sketch command would have
 * produced for the Stillpoint project, reading from
 * `content/context.ts` (the .spruce.md). It establishes visual direction
 * — typography, color, texture, motion, iconography — before /foundations
 * commits to specific tokens.
 *
 * Two exports:
 *   - stillpointSketch         — structured object for programmatic access
 *   - stillpointSketchMarkdown — full markdown rendering for catalog
 *                                illustrations
 *
 * The sketch produces direction, not commitment. /foundations is what
 * codifies the direction into tokens.
 */

export const stillpointSketch = {
  referenceImagery:
    'Real people, natural light, organic textures. Moments of presence and calm — a person breathing in a window, mountains at dusk, a single lit candle next to a ceramic vase, soft abstract organic shapes in sage and lavender. Avoid perfect "wellness influencer" imagery; lean toward the everyday and the imperfect.',
  typography:
    "A humanist sans (Söhne — clarity, warmth, modern human connection) paired with a thoughtful serif (Lora — editorial moments, longer-form content). Söhne handles UI, body, and most display. Lora carries editorial moments — quotes, longer-form session intros, marketing headers. The pairing avoids both the AI-default geometric sans and the meditation-app handwritten cliché. It commits to typography that respects users as thoughtful adults.",
  color:
    "Warm-leaning neutral foundation in cream and warm sand. Sage as the primary accent — soft enough to feel grounding, present enough to anchor structure. Deep indigo as a depth anchor for type and structural elements. Lavender and sunset peach as restrained accents for moments of warmth and energy in interactive elements (buttons, notifications, selected states). The palette commits to warm earth tones with deliberate accents, avoiding both meditation-app pastel-everything and SaaS cool-blue-with-purple-accent.",
  textureAndMaterial:
    "Paper-like and organic. Surfaces feel like soft paper or matte ceramic — not glossy, not glassy. Subtle warmth in the texture; nothing slick or technical. When dimension is needed, lean on quiet shadows and gentle gradients, not bold elevation.",
  iconography:
    "Line-based, rounded corners, consistent 2px stroke weight, open and friendly. Matches the typography's humanist warmth — no sharp geometric shapes, no aggressive angles. Icons feel hand-drawn but precise, like they belong to the same family.",
  layoutArchetypes:
    "Editorial spreads and narrative scrolls, not dashboard grids. Generous spacing that signals breathing room. Asymmetric balance over rigid symmetry — but quietly asymmetric, not aggressively so. Content-forward; chrome-light. The layouts feel more like a thoughtful magazine than a SaaS app.",
  motion:
    "Slow and settled. Strong deceleration so arrivals feel calm rather than snappy. Durations in the 300–500ms range for primary transitions; 150ms for direct manipulation feedback. Motion should feel unhurried, never urgent. Never autoplay or auto-advance.",
  antiReferences:
    'Should NOT feel like Calm or Headspace\'s most polished marketing pages (too commercial, too produced). Should NOT use generic wellness photography of women in sun-drenched windows. Should NOT use the SaaS-default cool-blue-and-purple palette. Should NOT use loud gradients or aggressive color blocks. Should NOT feel performative — no "join thousands of users" social proof, no exclamation points, no urgency cues.',
  notes:
    'The brand promise is "Mindfulness for real life." Everything should feel grounded in actual lived experience, not aspirational fantasy.',
} as const;

export const stillpointSketchMarkdown = `# Sketch — Visual Direction

Generated by /sketch from .spruce.md. Direction, not commitment — /foundations codifies the tokens that follow from this brief.

---

## Reference imagery

${stillpointSketch.referenceImagery}

## Typography

${stillpointSketch.typography}

## Color

${stillpointSketch.color}

## Texture and material

${stillpointSketch.textureAndMaterial}

## Iconography

${stillpointSketch.iconography}

## Layout archetypes

${stillpointSketch.layoutArchetypes}

## Motion

${stillpointSketch.motion}

## Anti-references

${stillpointSketch.antiReferences}

---

## Notes

${stillpointSketch.notes}
`;
