/**
 * Stillpoint .sketch.md content.
 *
 * This is the visual direction file Spruce’s /sketch command would have
 * produced for the Stillpoint project, reading from
 * `content/context.ts` (the .spruce.md). It establishes visual direction
 * — typography, color, texture, motion, iconography — before /foundations
 * commits to specific tokens.
 *
 * Two exports:
 *   - stillpointSketch         — structured object for programmatic access
 *   - stillpointSketchMarkdown — full markdown rendering for catalog
 *                                illustrations
 *
 * The sketch produces direction, not commitment. /foundations is what
 * codifies the direction into tokens.
 */

export const stillpointSketch = {
  referenceImagery:
    'Real people, natural light, organic textures. Moments of presence and calm — a person breathing in a window, mountains at dusk, a single lit candle next to a ceramic vase, soft abstract organic shapes in sage and lavender. Avoid perfect "wellness influencer" imagery; lean toward the everyday and the imperfect.',
  typography:
    "A humanist sans for clarity and modern warmth, paired with an editorial serif for longer-form moments — quotes, longer-form session intros, marketing headers. The sans handles UI, body, and most display; the serif carries the editorial register. Candidates that fit the character: Söhne, Halyard, or Inter Display for the sans; Lora, Tiempos, or Newsreader for the serif. /foundations picks the specific pair. The character avoids both the AI-default geometric sans and the meditation-app handwritten cliché — typography that respects users as thoughtful adults.",
  color:
    "Warm-leaning neutral foundation in cream and warm sand. Sage as the primary accent — soft enough to feel grounding, present enough to anchor structure. Deep indigo as a depth anchor for type and structural elements. Lavender and sunset peach as restrained accents for moments of warmth and energy in interactive elements (buttons, notifications, selected states). Palette character — warm earth tones with deliberate accents, avoiding both meditation-app pastel-everything and SaaS cool-blue-with-purple-accent. Specific values are /foundations’ work.",
  textureAndMaterial:
    "Paper-like and organic. Surfaces feel like soft paper or matte ceramic — not glossy, not glassy. Subtle warmth in the texture; nothing slick or technical. When dimension is needed, lean on quiet shadows and gentle gradients, not bold elevation.",
  iconography:
    "Line-based with rounded corners and a consistent thin stroke — open and friendly. Matches the typography’s humanist warmth: no sharp geometric shapes, no aggressive angles. Icons feel hand-drawn but precise, like they belong to the same family. Specific stroke weight, scale, and grid set in /foundations.",
  layoutArchetypes:
    "Editorial spreads and narrative scrolls, not dashboard grids. Generous spacing that signals breathing room. Asymmetric balance over rigid symmetry — but quietly asymmetric, not aggressively so. Content-forward; chrome-light. The layouts feel more like a thoughtful magazine than a SaaS app.",
  motion:
    "Slow and settled. Strong deceleration so arrivals feel calm rather than snappy. Primary transitions in the slow range (around 300–500ms); direct-manipulation feedback stays fast (under 200ms). Motion should feel unhurried, never urgent. Never autoplay or auto-advance. Specific durations and easing curves committed in /foundations.",
  antiReferences:
    'Should NOT feel like Calm or Headspace\'s most polished marketing pages (too commercial, too produced). Should NOT use generic wellness photography of women in sun-drenched windows. Should NOT use the SaaS-default cool-blue-and-purple palette. Should NOT use loud gradients or aggressive color blocks. Should NOT feel performative — no "join thousands of users" social proof, no exclamation points, no urgency cues.',
  notes:
    'The brand promise is "Mindfulness for real life." Everything should feel grounded in actual lived experience, not aspirational fantasy.',
} as const;

export const stillpointSketchMarkdown = `# Sketch — Visual Direction

Generated by /sketch from .spruce.md. Direction, not commitment — /foundations codifies the tokens that follow from this brief.

---

## Reference imagery

${stillpointSketch.referenceImagery}

## Typography

${stillpointSketch.typography}

## Color

${stillpointSketch.color}

## Texture and material

${stillpointSketch.textureAndMaterial}

## Iconography

${stillpointSketch.iconography}

## Layout archetypes

${stillpointSketch.layoutArchetypes}

## Motion

${stillpointSketch.motion}

## Anti-references

${stillpointSketch.antiReferences}

---

## Notes

${stillpointSketch.notes}
`;
