import { SpecimenFrame } from "./DemoFrame";

/**
 * /design demo. A single captioned sample output — what /design produces in
 * one pass given the meditation-app context (from /spruce-up) and the
 * foundations (from /foundations).
 *
 * Renders a "Today" home screen for the meditation app: a small date-strip
 * header at the top, the featured "Tonight" practice as the hero, and two
 * smaller "Also tonight" cards as alternative practice options. Multiple
 * compositional elements at varying weight — the screen reads as a real
 * designed app surface rather than a single card centered in a frame.
 *
 * No toggle, no progression, no markers. The artifact stands as the
 * demonstration. The caption below names what was generated.
 */

const LORA = 'var(--font-lora), Georgia, "Times New Roman", serif';
const SOURCE_SANS = "var(--font-source-sans), system-ui, sans-serif";

type AltPractice = {
  title: string;
  description: string;
  duration: string;
};

const ALTERNATIVES: AltPractice[] = [
  {
    title: "Body scan",
    description: "Notice the body, head to feet.",
    duration: "10 min",
  },
  {
    title: "For sleep",
    description: "For nights when sleep won't come.",
    duration: "15 min",
  },
];

export function DesignDemo() {
  return (
    <SpecimenFrame
      eyebrow="Specimen"
      scope="Generated by /design"
      caption="Generated end-to-end from the meditation-app context — composing the typography, palette, spacing, and primitives /foundations established into a complete home surface."
    >
      {/* Card stage uses the meditation-app Canvas color, same as
          /foundations and /spruce-up's completion file, so the workflow
          narrative carries across demos. */}
      <div
        className="border border-stone-200 rounded-md px-6 py-10 md:px-10 md:py-12"
        style={{ backgroundColor: "#FAFAF9" }}
      >
        <div
          className="max-w-lg mx-auto"
          style={{ fontFamily: SOURCE_SANS }}
        >
          {/* Date strip — situates the screen in the moment, not just the
              date. "Tuesday evening" reads as on-character context for the
              meditation app rather than generic app chrome. */}
          <div className="mb-9">
            <p className="font-mono text-2xs uppercase tracking-widest text-stone-500">
              Tuesday evening
            </p>
          </div>

          {/* Hero: featured Tonight practice. No card container — the hero
              is the freest visual moment on the screen, set off by space
              rather than by a box. The secondary cards below get
              containers; the hierarchy is "biggest = freest, smaller =
              contained." */}
          <article className="mb-10">
            <p className="font-mono text-2xs uppercase tracking-widest text-stone-500 mb-4">
              Tonight
            </p>
            <h3
              className="text-3xl text-stone-900 leading-[1.1] tracking-tight mb-3"
              style={{ fontFamily: LORA }}
            >
              Evening practice
            </h3>
            <p className="text-base text-stone-700 leading-relaxed mb-6 max-w-prose">
              Settle the day. Five minutes of guided breath — sit or lie
              down.
            </p>
            {/* Metadata strip — duration + format. No inner hairline; the
                CTA's own visual weight separates it from the metadata, and
                the section divider below handles hero/secondary. */}
            <div className="flex items-center gap-2.5 mb-7">
              <span className="font-mono text-2xs uppercase tracking-widest text-stone-500">
                5 minutes
              </span>
              <span aria-hidden className="text-stone-400">
                ·
              </span>
              <span className="font-mono text-2xs uppercase tracking-widest text-stone-500">
                Guided
              </span>
            </div>
            <button
              type="button"
              className="bg-amber-700 text-white text-sm font-medium px-5 py-2 rounded-md hover:bg-amber-800 transition-colors"
            >
              Begin
            </button>
          </article>

          {/* Hairline divider before secondary section */}
          <div className="border-t border-stone-200 mb-8" />

          {/* Secondary: "Also tonight" — alternative practices stacked
              vertically as full-width contained rows. Avoids the equal-
              weight 2-col grid pattern; reads as a list of options at
              quieter visual weight than the hero above. */}
          <section>
            <p className="font-mono text-2xs uppercase tracking-widest text-stone-500 mb-4">
              Also tonight
            </p>
            <div className="space-y-2.5">
              {ALTERNATIVES.map((alt) => (
                <AltCard key={alt.title} {...alt} />
              ))}
            </div>
          </section>
        </div>
      </div>

    </SpecimenFrame>
  );
}

// ---------------------------------------------------------------------------
// AltCard — full-width contained row used in the "Also tonight" secondary
// stack. Title and duration share the top line (justify-between) with the
// description below. Stone-100 fill to read as distinct from the page
// Canvas (#FAFAF9).
// ---------------------------------------------------------------------------

function AltCard({ title, description, duration }: AltPractice) {
  return (
    <div className="bg-stone-100 border border-stone-200 rounded-md px-4 py-3">
      <div className="flex items-baseline justify-between gap-3 mb-1">
        <p
          className="text-base text-stone-900 leading-tight"
          style={{ fontFamily: LORA }}
        >
          {title}
        </p>
        <p
          className="font-mono text-2xs uppercase tracking-widest text-stone-500 shrink-0"
          style={{ fontFamily: SOURCE_SANS }}
        >
          {duration}
        </p>
      </div>
      <p
        className="text-xs text-stone-700 leading-snug"
        style={{ fontFamily: SOURCE_SANS }}
      >
        {description}
      </p>
    </div>
  );
}
