import type { ReactNode } from "react";
import { SpecimenFrame } from "./DemoFrame";

/**
 * /foundations demo. A static specimen sheet — the artifact /foundations
 * produces, rendered in the catalog's editorial register.
 *
 * Three movements with varying weights:
 *   1. Type (hero, full width) — Lora display + Source Sans body
 *   2. Color (full-width band) — five swatches across the row
 *   3. Composed + Space (paired) — the composition on the left, its
 *      spacing scale alongside on the right (narrower, since Space is
 *      shown as the scale the composition uses, not as a sibling
 *      foundational layer to Color)
 *
 * Hairline rules separate the three movements. The pairing of Composed
 * with Space is conceptual: Color and Type are broad foundational layers
 * shown at full width; Space is the underlying scale the composition
 * actually uses, so it sits alongside the proof rather than beside Color.
 *
 * Sample product context continues from /spruce-up: a meditation app for
 * parents — warm-paper neutrals + warm amber accent (honey / evening light),
 * humanist serif + sans pairing, generous spacing. The visitor who reads
 * /spruce-up first sees the through-line: interview answers → these
 * specific tokens.
 */

const LORA = 'var(--font-lora), Georgia, "Times New Roman", serif';
const SOURCE_SANS = "var(--font-source-sans), system-ui, sans-serif";

const SWATCHES: Array<{ label: string; value: string }> = [
  { label: "Canvas", value: "#FAFAF9" },
  { label: "Surface", value: "#F5F5F4" },
  { label: "Ink", value: "#1C1917" },
  { label: "Muted", value: "#57534E" },
  { label: "Accent", value: "#B45309" },
];

const SPACE_STEPS = [4, 8, 16, 24, 32, 48];

export function FoundationsDemo() {
  return (
    <SpecimenFrame
      eyebrow="Specimen"
      scope="Generated by /foundations"
      caption="Tokens and primitives generated for the meditation-app context captured by /spruce-up. Every other Spruce command composes within these foundations."
    >
      {/* Card stage — note the warm background bias: the meditation-app
          context's Canvas token is what this surface would be in the
          generated system, so the demo card itself uses that palette. */}
      <div className="border border-stone-200 rounded-md px-7 py-9 md:px-10 md:py-11" style={{ backgroundColor: "#FAFAF9" }}>
        {/* Hero: Type — the largest moment. Display in Lora, body in Source
            Sans 3. The serif/humanist-sans pair is the typographic decision
            /foundations would make for this product context. */}
        <Section eyebrow="Type">
          <p
            className="text-3xl md:text-4xl leading-[1.1] tracking-tight text-stone-900 mb-4"
            style={{ fontFamily: LORA }}
          >
            Recover, don&rsquo;t transform.
          </p>
          <p
            className="text-base md:text-lg text-stone-700 leading-relaxed max-w-prose"
            style={{ fontFamily: SOURCE_SANS }}
          >
            Short-session meditation for parents — five-minute practices
            designed to fit into the gaps of a busy day.
          </p>
        </Section>

        <Divider />

        {/* Middle: Color as a full-width band. Five swatches need horizontal
            range — letting Color take the full row gives them the room
            they need without competing for space with Space. */}
        <Section eyebrow="Color">
          <ColorSwatches />
        </Section>

        <Divider />

        {/* Close: Composed primitive paired with Space. Composed shows the
            tokens in use; Space sits alongside as the scale that composition
            actually uses — conceptually the right pairing, since Space is
            the underlying gap system and the card visibly applies it. */}
        <div className="grid grid-cols-12 gap-y-8 sm:gap-x-10">
          <div className="col-span-12 sm:col-span-8">
            <Section eyebrow="Composed">
              <PrimitiveExample />
            </Section>
          </div>
          <div className="col-span-12 sm:col-span-4">
            <Section eyebrow="Space">
              <SpacingScale />
            </Section>
          </div>
        </div>
      </div>

    </SpecimenFrame>
  );
}

// ---------------------------------------------------------------------------
// Section — eyebrow above content. Used by all three movements.
// ---------------------------------------------------------------------------

function Section({
  eyebrow,
  children,
}: {
  eyebrow: string;
  children: ReactNode;
}) {
  return (
    <section>
      <p
        className="font-mono text-2xs uppercase tracking-widest text-stone-500 mb-4"
        style={{ fontFamily: SOURCE_SANS }}
      >
        {eyebrow}
      </p>
      {children}
    </section>
  );
}

function Divider() {
  return <div className="border-t border-stone-200 my-8 md:my-10" />;
}

// ---------------------------------------------------------------------------
// ColorSwatches — five tokens shown as a horizontal row of swatches with
// display name + hex value below each.
// ---------------------------------------------------------------------------

function ColorSwatches() {
  return (
    <div className="flex gap-2.5 sm:gap-3">
      {SWATCHES.map((s) => (
        <div key={s.label} className="flex-1 min-w-0">
          <div
            className="h-12 rounded-sm border border-stone-200"
            style={{ backgroundColor: s.value }}
            aria-label={s.label}
          />
          <p
            className="text-xs text-stone-700 mt-2 truncate"
            style={{ fontFamily: SOURCE_SANS }}
          >
            {s.label}
          </p>
          <p className="font-mono text-2xs text-stone-500 truncate">
            {s.value}
          </p>
        </div>
      ))}
    </div>
  );
}

// ---------------------------------------------------------------------------
// SpacingScale — six scale steps as horizontal bars with px labels. Bars
// scaled visually (px*2) so they fit the narrower column the scale lives
// in (paired with the composed primitive at the bottom). Smallest step
// (4px) still produces a visible 8px bar.
// ---------------------------------------------------------------------------

function SpacingScale() {
  return (
    <div className="space-y-2">
      {SPACE_STEPS.map((px) => (
        <div key={px} className="flex items-center gap-2.5">
          <div
            className="bg-stone-700 h-1.5 rounded-sm"
            style={{ width: `${px * 2}px` }}
            aria-hidden
          />
          <p
            className="font-mono text-2xs text-stone-500"
            aria-label={`${px} pixels`}
          >
            {px}
          </p>
        </div>
      ))}
    </div>
  );
}

// ---------------------------------------------------------------------------
// PrimitiveExample — small composed card using every token category in the
// specimen above: stone neutrals, Lora display, Source Sans body, mono
// caps eyebrow, rose accent on the CTA, scale-conformant spacing.
// ---------------------------------------------------------------------------

function PrimitiveExample() {
  return (
    <div className="border border-stone-200 rounded-md p-5 max-w-sm" style={{ backgroundColor: "#F5F5F4" }}>
      <p
        className="font-mono text-2xs uppercase tracking-widest text-stone-500 mb-2"
        style={{ fontFamily: SOURCE_SANS }}
      >
        Tonight
      </p>
      <p
        className="text-xl text-stone-900 mb-2 leading-tight"
        style={{ fontFamily: LORA }}
      >
        Evening practice
      </p>
      <p
        className="text-sm text-stone-700 mb-4 leading-relaxed"
        style={{ fontFamily: SOURCE_SANS }}
      >
        Settle the day. Five minutes of guided breath.
      </p>
      <button
        type="button"
        className="bg-amber-700 text-white text-sm font-medium px-3 py-1.5 rounded-md hover:bg-amber-800 transition-colors"
        style={{ fontFamily: SOURCE_SANS }}
      >
        Begin →
      </button>
    </div>
  );
}
