import { SpecimenFrame } from "./DemoFrame";

/**
 * /remix demo. Three genuinely distinct directions for the same brief —
 * "an evening practice card" in the meditation-app context that threads
 * through /spruce-up, /foundations, /design, and /decide. Same product,
 * same surface, same content; three different commitments in typography,
 * color, character register, and voice.
 *
 * The mechanic — three side-by-side variants at equal fidelity — is the
 * command's argument made visible. Visitors see three different products
 * at once, can compare directly, and pick the one that resonates. No
 * ranking, no toggle, no "best one and two alternatives." That's how
 * /remix works in the terminal, and that's how the demo reads.
 *
 * Distinctness operates at the level the reference file describes: each
 * variant differs in character register (editorial / technical /
 * expressive), typeface, palette temperature, and voice. Not three
 * variations on a theme — three different points of view.
 */

const LORA = 'var(--font-lora), Georgia, "Times New Roman", serif';
const SOURCE_SANS = "var(--font-source-sans), system-ui, sans-serif";
const PLEX_SANS = "var(--font-plex-sans), system-ui, sans-serif";
const PLEX_MONO = "var(--font-plex-mono), ui-monospace, monospace";
const MONA_SANS = "var(--font-mona-sans), system-ui, sans-serif";

export function RemixDemo() {
  return (
    <SpecimenFrame
      eyebrow="Specimen"
      scope="Generated by /remix · same brief, three directions"
      caption="Same product, same surface, same content. Three different points of view — each one a defensible answer to the same brief."
    >
      {/* Card stage. The grid is single-column on mobile and three-column
          at md+; visitors see all three variants side-by-side at desktop
          (the command's argument), stacked at mobile (legibility wins). */}
      <div className="border border-rule-subtle bg-surface rounded-md px-5 py-7 md:px-7 md:py-9">
        <div className="grid grid-cols-1 md:grid-cols-3 gap-x-5 gap-y-7">
          <Variant label="Editorial">
            <EditorialCard />
          </Variant>
          <Variant label="Technical">
            <TechnicalCard />
          </Variant>
          <Variant label="Expressive">
            <ExpressiveCard />
          </Variant>
        </div>
      </div>
    </SpecimenFrame>
  );
}

// ---------------------------------------------------------------------------
// Variant — wraps each direction with a labeled eyebrow above the mockup.
// The eyebrow is editorial (mono caps, accent-colored) so the labels
// distinguish the variants at a glance, per the command's spec: "labels
// matter — they're what the user scans first."
// ---------------------------------------------------------------------------

function Variant({
  label,
  children,
}: {
  label: string;
  children: React.ReactNode;
}) {
  return (
    <div>
      <p className="font-mono text-2xs uppercase tracking-widest text-accent mb-3">
        {label}
      </p>
      {children}
    </div>
  );
}

// ---------------------------------------------------------------------------
// Editorial — restrained, literary. Lora display + Source Sans body, warm
// paper Canvas, italic prompt, link-styled action. The variant that would
// belong on a literary magazine's app — the meditation app as quiet
// publication.
// ---------------------------------------------------------------------------

function EditorialCard() {
  return (
    <div
      className="border border-stone-200 rounded-md px-4 py-5"
      style={{ backgroundColor: "#FAFAF9" }}
    >
      <p
        className="font-mono text-2xs uppercase tracking-widest text-stone-500 mb-3"
        style={{ fontFamily: SOURCE_SANS }}
      >
        Tuesday evening
      </p>
      <h4
        className="text-2xl text-stone-900 leading-tight tracking-tight mb-3 italic font-normal"
        style={{ fontFamily: LORA }}
      >
        Evening practice
      </h4>
      <p
        className="text-sm text-stone-700 leading-relaxed mb-5"
        style={{ fontFamily: SOURCE_SANS }}
      >
        Five minutes of guided breath. Sit or lie down — whichever helps you
        let go.
      </p>
      <p
        className="text-sm text-amber-700 font-medium"
        style={{ fontFamily: SOURCE_SANS }}
      >
        Begin →
      </p>
    </div>
  );
}

// ---------------------------------------------------------------------------
// Technical — clinical, precise. Plex Sans + Plex Mono, slate-cool palette,
// data-forward time/duration label, programmatic voice ("Programmed for
// end-of-day"), button-styled action. The meditation app as developer tool.
// ---------------------------------------------------------------------------

function TechnicalCard() {
  return (
    <div
      className="border border-slate-200 rounded-sm px-4 py-5"
      style={{ backgroundColor: "#F8FAFC" }}
    >
      <p
        className="text-2xs uppercase tracking-widest text-slate-500 mb-3 font-medium"
        style={{ fontFamily: PLEX_MONO }}
      >
        21:14 · 5 min
      </p>
      <h4
        className="text-lg text-slate-900 leading-tight tracking-tight mb-3 font-medium"
        style={{ fontFamily: PLEX_SANS }}
      >
        Evening practice
      </h4>
      <p
        className="text-sm text-slate-700 leading-snug mb-5"
        style={{ fontFamily: PLEX_SANS }}
      >
        Guided breathwork. Programmed for end-of-day recovery.
      </p>
      <button
        type="button"
        className="text-xs text-white bg-teal-700 px-3 py-1.5 rounded-sm font-medium"
        style={{ fontFamily: PLEX_SANS }}
      >
        Start ▸
      </button>
    </div>
  );
}

// ---------------------------------------------------------------------------
// Expressive — bold, confident. Mona Sans heavy display, warm dark surface,
// large CTA, deeply saturated accent. The meditation app as performance
// product — adjacent in feel to a high-end fitness or sports app, but
// holding the meditation content. Same brief, much louder voice.
// ---------------------------------------------------------------------------

function ExpressiveCard() {
  return (
    <div
      className="rounded-md px-4 py-5 text-white"
      style={{ backgroundColor: "#0F2D2D" }}
    >
      <p
        className="text-2xs uppercase tracking-widest mb-3 font-bold"
        style={{ fontFamily: MONA_SANS, color: "#FB923C" }}
      >
        Tonight
      </p>
      <h4
        className="text-2xl leading-[1.05] tracking-tight mb-3 font-bold"
        style={{ fontFamily: MONA_SANS }}
      >
        Wind down.
      </h4>
      <p
        className="text-sm leading-snug mb-5 text-emerald-100"
        style={{ fontFamily: MONA_SANS }}
      >
        Five minutes. Breathe and reset.
      </p>
      <button
        type="button"
        className="text-sm font-bold px-4 py-2 rounded-md w-full"
        style={{ fontFamily: MONA_SANS, backgroundColor: "#FB923C", color: "#0F2D2D" }}
      >
        Begin
      </button>
    </div>
  );
}
